export const stageEnums: {
  NEW: "NEW";
  GIF_PENDING: "GIF_PENDING";
  MESSAGE_PENDING: "MESSAGE_PENDING";
  GIF_SAVED: "GIF_SAVED";
} = {
  NEW: "NEW",
  GIF_PENDING: "GIF_PENDING",
  MESSAGE_PENDING: "MESSAGE_PENDING",
  GIF_SAVED: "GIF_SAVED",
};
