export const stageEnums: {
  NEW: "NEW";
  GIF_PENDING: "GIF_PENDING";
  WAIT_FOR_INDEX: "WAIT_FOR_INDEX";
  GIF_SAVED: "GIF_SAVED";
  EDIT: "EDIT";
} = {
  NEW: "NEW",
  GIF_PENDING: "GIF_PENDING",
  WAIT_FOR_INDEX: "WAIT_FOR_INDEX",
  GIF_SAVED: "GIF_SAVED",
  EDIT: "EDIT",
};
